### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by turian** [RightTyper/RightTyper#12]
I am excited to try RightTyper. I installed it and ran it on a brief pytorch run (like 30 seconds, validation only, no training) but get this error:

```
[2024-08-30 10:18:52,798][righttyper][ERROR] - IndexError in annotations
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.12.5/envs/torch312/lib/python3.12/site-packages/righttyper/righttyper.py", line 569, in output_type_signatures
    annotations = [visited_funcs_arguments[t][index].arg_name + ": " + annotation.format(union_typeset_str(t.file_name, visited_funcs_arguments[t][index].type_name_set, {})) for index, annotation in enumerate(annotations)]
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range
```

**Comment by turian** [comment]
FYI this is using Lightning 2x framework

**Comment by turian** [comment]
Running from [d7f8b14](https://github.com/RightTyper/RightTyper/commit/d7f8b14dd2f8bf6a7e53c9b8deba013975275a17) the error is similar:

```
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/torch312/lib/python3.12/site-packages/righttyper/righttyper.py", line 581, in output_type_signatures
    visited_funcs_arguments[t][index].arg_name
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
IndexError: list index out of range
```

From doing some print debug output, it is failing on a class that is not being used in my run (an nn.Module that I am disabling choosing using hydra config).

If you show me what kind of debugging / log output you need, I can give more details.

**Comment by emeryberger** [comment]
Can you retry with the repo version?

`python3 -m pip install git+https://github.com/righttyper/righttyper`

This should generate a log output message in `righttyper.log`.

**Comment by emeryberger** [comment]
If you can provide a [minimal working example](https://en.wikipedia.org/wiki/Minimal_reproducible_example), that would be ideal.

**Comment by emeryberger** [comment]
Ping @turian

**Comment by emeryberger** [comment]
Can't reproduce, closing for lack of response.
