### ISSUE TITLE
RightTyper gets stuck on `httpie`

### ISSUE THREAD

**Issue by emeryberger** [RightTyper/RightTyper#53]
# To reproduce:

## Install dependencies and run `pytest` with `righttyper`:

```bash
python3.12 -m venv py312-httpie
source py312-httpie/bin/activate
git clone https://github.com/httpie/cli.git
cd cli
```

Install [requirements.txt](https://github.com/user-attachments/files/17984040/requirements.txt) and run.

```bash
python3 -m pip install -r requirements.txt
python3 -m pip install git+https://github.com/RightTyper/RightTyper.git
python3 -m righttyper -m pytest cli/tests/test_httpie.py -s
```

## Output:

Gets stuck.

**Comment by jaltmayerpizzorno** [comment]
Using the version from https://github.com/RightTyper/RightTyper/pull/59, I can't reproduce the issue. It may have been related to the circular frame reference issue it fixes...
