### ISSUE TITLE
Allow the user to specify which methods/classes to annotate within a file

### ISSUE THREAD

**Issue by MDBijman** [RightTyper/RightTyper#65]
Currently when running RightTyper I can specify a set of files to annotate. It would be useful if I could limit the changes to specific methods or classes within those files, so that I can annotate my code on a more granular level. For example, if I want to annotate methods starting with `foo` within `file_to_annotate`:

`python3 -m righttyper --all-files --include-files file_to_annotate.py --include-methods "foo*" --srcdir=. file.py`

**Comment by emeryberger** [comment]
Done, added as `--include-functions`. Note that this is truly matching regular expressions, not globs (as with `--include-files`), which is arguably a potential source of confusion; `foo*` as a glob means anything starting with `foo`, but as a regex, it means `fo` followed by an arbitrary number of `o`s (possibly 0).

**Comment by emeryberger** [comment]
On second thought, removed globs, sticking with regexes.
